"""Command-line entry point for the churn training pipeline.

This module is intentionally the only place that reads runtime
configuration. It loads YAML, validates it into ``PipelineConfig``, resolves
project-relative paths, configures logging, and delegates stage execution to
``src.pipelines.pipeline.run_pipeline``.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import logging
import subprocess
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from uuid import uuid4

from pydantic import (
    AnyHttpUrl,
    BaseModel,
    ConfigDict,
    Field,
    ValidationError,
    model_validator,
)
from yaml import YAMLError

from src.config.loader import load_yaml_config
from src.pipelines.pipeline import run_pipeline
from src.storage.storage import get_project_root

logger = logging.getLogger(__name__)
DEFAULT_CONFIG_PATH = Path("config/pipeline.yaml")


class DatasetConfig(BaseModel):
    """Immutable details required to acquire and identify the raw dataset."""

    model_config = ConfigDict(extra="forbid")

    name: str = Field(min_length=1)
    url: AnyHttpUrl
    filename: str = Field(min_length=1)
    expected_sha256: str = Field(pattern=r"^[A-Fa-f0-9]{64}$")


class SchemaConfig(BaseModel):
    """The minimum data contract checked after ingestion."""

    model_config = ConfigDict(extra="forbid")

    target_column: str = Field(min_length=1)
    required_columns: list[str] = Field(min_length=1)


class SplitConfig(BaseModel):
    """Reproducible proportions used to split the cleaned dataset."""

    model_config = ConfigDict(extra="forbid")

    train_size: float = Field(gt=0, lt=1)
    validation_size: float = Field(ge=0, lt=1)
    test_size: float = Field(gt=0, lt=1)
    random_seed: int = Field(ge=0)
    stratify: bool = True

    @model_validator(mode="after")
    def sizes_must_sum_to_one(self) -> SplitConfig:
        total = self.train_size + self.validation_size + self.test_size
        if abs(total - 1.0) > 1e-9:
            raise ValueError("train_size, validation_size, and test_size must sum to 1.0")
        return self


class TrainingConfig(BaseModel):
    """Baseline model settings; the training stage will consume these later."""

    model_config = ConfigDict(extra="forbid")

    model_name: str = Field(min_length=1)
    random_seed: int = Field(ge=0)


class ArtifactsConfig(BaseModel):
    """Project-relative directory used for durable run outputs."""

    model_config = ConfigDict(extra="forbid")

    directory: Path


class PipelineConfig(BaseModel):
    """Full, validated configuration for one pipeline run."""

    model_config = ConfigDict(extra="forbid")

    pipeline_name: str = Field(min_length=1)
    dataset: DatasetConfig
    schema_config: SchemaConfig = Field(alias="schema")
    split: SplitConfig
    training: TrainingConfig
    artifacts: ArtifactsConfig


@dataclass(frozen=True)
class RunContext:
    """Runtime values generated by the entry point, never loaded from YAML."""

    run_id: str
    started_at: datetime
    project_root: Path
    config_path: Path
    config_sha256: str
    artifact_dir: Path
    git_commit: str | None


class ConfigurationError(Exception):
    """Raised when a configuration file cannot be loaded or validated."""


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse the optional path that selects the sole runtime config file."""
    parser = argparse.ArgumentParser(description="Run the customer churn training pipeline.")
    parser.add_argument(
        "--config",
        type=Path,
        default=DEFAULT_CONFIG_PATH,
        help="Project-relative or absolute YAML configuration path.",
    )
    return parser.parse_args(argv)


def load_config(config_path: Path) -> tuple[PipelineConfig, str]:
    """Safely load and validate one YAML config file, returning its SHA-256."""
    if not config_path.is_file():
        raise ConfigurationError(f"Configuration file not found: {config_path}")
    if config_path.suffix.lower() not in {".yaml", ".yml"}:
        raise ConfigurationError("Configuration file must use a .yaml or .yml extension")

    try:
        raw_text = config_path.read_text(encoding="utf-8")
        raw_config = load_yaml_config(config_path)
    except (OSError, TypeError, YAMLError) as exc:
        raise ConfigurationError(f"Could not load configuration: {exc}") from exc

    try:
        config = PipelineConfig.model_validate(raw_config)
    except ValidationError as exc:
        raise ConfigurationError(f"Invalid configuration:\n{exc}") from exc

    return config, hashlib.sha256(raw_text.encode("utf-8")).hexdigest()


def resolve_project_path(project_root: Path, configured_path: Path) -> Path:
    """Resolve a config path without allowing it to escape the project root."""
    candidate = configured_path if configured_path.is_absolute() else project_root / configured_path
    resolved = candidate.resolve()
    if not resolved.is_relative_to(project_root.resolve()):
        raise ConfigurationError(f"Configured path escapes the project root: {configured_path}")
    return resolved


def get_git_commit(project_root: Path) -> str | None:
    """Return the checked-out commit when Git is available, otherwise None."""
    try:
        completed = subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=project_root, capture_output=True,
            check=True, text=True, timeout=5,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    return completed.stdout.strip() or None


def create_run_context(config: PipelineConfig, project_root: Path, config_path: Path, config_sha256: str) -> RunContext:
    """Create a unique run directory and the metadata that identifies it."""
    artifact_root = resolve_project_path(project_root, config.artifacts.directory)
    run_id = f"{datetime.now(timezone.utc):%Y%m%dT%H%M%SZ}-{uuid4().hex[:8]}"
    artifact_dir = artifact_root / run_id
    artifact_dir.mkdir(parents=True, exist_ok=False)
    context = RunContext(
        run_id=run_id, started_at=datetime.now(timezone.utc), project_root=project_root,
        config_path=config_path, config_sha256=config_sha256, artifact_dir=artifact_dir,
        git_commit=get_git_commit(project_root),
    )
    write_run_metadata(context)
    return context


def write_run_metadata(context: RunContext) -> None:
    """Preserve the effective config and immutable identifiers for this run."""
    config_copy_path = context.artifact_dir / "pipeline.yaml"
    config_copy_path.write_text(context.config_path.read_text(encoding="utf-8"), encoding="utf-8")
    metadata = {
        "run_id": context.run_id,
        "started_at": context.started_at.isoformat(),
        "config_path": str(context.config_path.relative_to(context.project_root)),
        "config_sha256": context.config_sha256,
        "git_commit": context.git_commit,
    }
    (context.artifact_dir / "run_metadata.json").write_text(
        json.dumps(metadata, indent=2) + "\n", encoding="utf-8"
    )


def configure_logging() -> None:
    """Configure process-wide, CI-friendly logging once at application startup."""
    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s %(message)s",
        datefmt="%Y-%m-%dT%H:%M:%SZ",
    )


def main(argv: list[str] | None = None) -> int:
    """Run the pipeline and return an operating-system-compatible exit code."""
    configure_logging()
    try:
        args = parse_args(argv)
        project_root = get_project_root()
        config_path = resolve_project_path(project_root, args.config)
        config, config_sha256 = load_config(config_path)
        context = create_run_context(config, project_root, config_path, config_sha256)
        logger.info(
            "Starting pipeline run_id=%s pipeline=%s config_sha256=%s git_commit=%s",
            context.run_id, config.pipeline_name, context.config_sha256,
            context.git_commit or "unavailable",
        )
        result = run_pipeline(config, context)
        logger.info("Pipeline completed run_id=%s artifact_dir=%s result=%s", context.run_id, context.artifact_dir, result)
        return 0
    except ConfigurationError as exc:
        logger.error("Configuration error: %s", exc)
        return 2
    except Exception:
        logger.exception("Pipeline failed")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
